FORMAT: 1A
HOST: https://carve-api.herokuapp.com

# carve-api

Carve API makes it easy to convert PDFs into an array PNGs.

The carve-api is based on [CONTRA]() API design. [JSON](http://www.json.org) is returned in all responses from the API, including errors.

I've tried to make it as easy to use as possible, but if you have any feedback please [let me know](mailto:mot@mot.la).

## GET /api/v0/documents/create.json?url={url}&webhook={webhook}

Create a document to generate PNGs. Allows for POST or GET.

+ Parameters
  + url (required, string, `http://mot.la/assets/resume.pdf`) ... String `url` of the PDF to convert.
  + webhook (required, string, `http://requestb.in/nxwuxynx`) ... String `webhook` where the converted PNGs payload will be deposited.
  + postscript (string, `some_custom_string_value`) ... String `postscript` as a way to pass custom data as a string. Pass an ID or pass a stringified JSON payload. The choice is yours.

+ Response 200 (application/json)

    {
      "documents": [{
        "pages": [ ],
        "status": "unprocessed",
        "url": "http://mot.la/assets/resume.pdf",
        "webhook": "http://requestb.in/nxwuxynx"
      }]
    }

+ Response 500 (application/json)

    {
      "errors": [{
        "code": "required",
        "field": "url",
        "message": "url cannot be blank"
      }]
    }
